// This file is auto-generated by @hey-api/openapi-ts

export type ResponseCountDTO = {
  count: number;
};

export type ResponseUserDTO = {
  name: string;
  email: string;
  phone: string;
};

export type ResponseUsersDTO = {
  users: Array<ResponseUserDTO>;
};

export type RequestSignupDTO = {
  name: string;
  email: string;
  phone: string;
  password: string;
};

export type ResponseAuthorizedUserDTO = {
  id: number;
  name: string;
  email: string;
  phone: string;
};

export type ResponseLoggedInDTO = {
  user: ResponseAuthorizedUserDTO;
  accessToken: string;
};

export type RequestLoginDTO = {
  email: string;
  password: string;
};

export type UsersControllerCountResponse = ResponseCountDTO;

export type UsersControllerCountError = unknown;

export type UsersControllerFindByIdData = {
  path: {
    id: number;
  };
};

export type UsersControllerFindByIdResponse = ResponseUserDTO;

export type UsersControllerFindByIdError = unknown;

export type UsersControllerFindAllData = {
  query: {
    limit?: number;
    page: number;
  };
};

export type UsersControllerFindAllResponse = ResponseUsersDTO;

export type UsersControllerFindAllError = unknown;

export type AuthControllerSignupData = {
  body: RequestSignupDTO;
};

export type AuthControllerSignupResponse = ResponseLoggedInDTO;

export type AuthControllerSignupError = unknown;

export type AuthControllerLoginData = {
  body: RequestLoginDTO;
};

export type AuthControllerLoginResponse = ResponseLoggedInDTO;

export type AuthControllerLoginError = unknown;

export type AuthControllerMeResponse = ResponseAuthorizedUserDTO;

export type AuthControllerMeError = unknown;
